import { FieldType, SelectableValue } from './grafana';
export const TABLE_NAME_INCIDENT = 'incident';
export const TABLE_NAME_CHANGE_REQUEST = 'change_request';
export const TABLE_NAME_PROBLEM = 'problem';
export const TABLE_NAMES: SelectableValue[] = [
  { label: 'Incidents (INC)', value: TABLE_NAME_INCIDENT, short_code: 'INC' },
  { label: 'Change Request (CHG)', value: TABLE_NAME_CHANGE_REQUEST, short_code: 'CHG' },
  { label: 'Problem (PRB)', value: TABLE_NAME_PROBLEM, short_code: 'PRB' },
];
export const QUERY_TYPES: SelectableValue[] = [
  { label: 'Table', value: 'table' },
  { label: 'Stats', value: 'stats' },
];
export const RESULT_FORMATS: SelectableValue[] = [
  { label: 'Table', value: 'table' },
  { label: 'Time Series', value: 'timeseries' },
];
export const FIELDS_LIST: SelectableValue[] = [
  { value: 'active', label: 'Active', tables: [TABLE_NAME_INCIDENT, TABLE_NAME_CHANGE_REQUEST, TABLE_NAME_PROBLEM] },
  { value: 'assigned_to', label: 'Assigned To', tables: [TABLE_NAME_INCIDENT, TABLE_NAME_CHANGE_REQUEST, TABLE_NAME_PROBLEM] },
  { value: 'assignment_group.name', label: 'Assignment Group', tables: [TABLE_NAME_INCIDENT, TABLE_NAME_CHANGE_REQUEST, TABLE_NAME_PROBLEM] },
  { value: 'assignment_group', label: 'Assignment Group ID', tables: [TABLE_NAME_INCIDENT, TABLE_NAME_CHANGE_REQUEST, TABLE_NAME_PROBLEM] },
  {
    value: 'description',
    label: 'Description',
    tables: [TABLE_NAME_INCIDENT, TABLE_NAME_CHANGE_REQUEST, TABLE_NAME_PROBLEM],
  },
  { value: 'end_date', label: 'End Date', tables: [TABLE_NAME_CHANGE_REQUEST], FieldType: FieldType.time },
  { value: 'incident_state', label: 'Incident State', tables: [TABLE_NAME_INCIDENT] },
  { value: 'number', label: 'Number', tables: [TABLE_NAME_INCIDENT, TABLE_NAME_CHANGE_REQUEST, TABLE_NAME_PROBLEM] },
  { value: 'opened_at', label: 'Opened At', tables: [TABLE_NAME_INCIDENT, TABLE_NAME_CHANGE_REQUEST, TABLE_NAME_PROBLEM], FieldType: FieldType.time },
  { value: 'priority', label: 'Priority', tables: [TABLE_NAME_INCIDENT, TABLE_NAME_CHANGE_REQUEST, TABLE_NAME_PROBLEM] },
  { value: 'short_description', label: 'Short Description', tables: [TABLE_NAME_INCIDENT, TABLE_NAME_CHANGE_REQUEST, TABLE_NAME_PROBLEM] },
  { value: 'start_date', label: 'Start Date', tables: [TABLE_NAME_CHANGE_REQUEST], FieldType: FieldType.time },
  { value: 'state', label: 'State', tables: [TABLE_NAME_INCIDENT, TABLE_NAME_CHANGE_REQUEST, TABLE_NAME_PROBLEM] },
  { value: 'sys_created_by', label: 'Created By', tables: [TABLE_NAME_INCIDENT, TABLE_NAME_CHANGE_REQUEST, TABLE_NAME_PROBLEM] },
  {
    value: 'sys_created_on',
    label: 'Created On',
    tables: [TABLE_NAME_INCIDENT, TABLE_NAME_CHANGE_REQUEST, TABLE_NAME_PROBLEM],
    FieldType: FieldType.time,
  },
  { value: 'urgency', label: 'Urgency', tables: [TABLE_NAME_PROBLEM] },
  { value: 'category', label: 'Category', tables: [TABLE_NAME_PROBLEM] },
  { value: 'subcategory', label: 'Subcategory', tables: [TABLE_NAME_PROBLEM] },
];
export const FIELDS_LIST_TIME = FIELDS_LIST.filter(f => f.FieldType === FieldType.time);
export const FILTER_CONDITIONS: SelectableValue[] = [
  { value: '^', label: 'AND' },
  { value: '^OR', label: 'OR' },
];
export const FILTER_OPERATIONS: SelectableValue[] = [
  { value: '=', label: 'Equals' },
  { value: '!=', label: 'Not Equals' },
  { value: '<', label: 'Less than' },
  { value: '<=', label: 'Less than or Equals' },
  { value: '>', label: 'Greater than' },
  { value: '>=', label: 'Greater than or Equals' },
  { value: 'STARTSWITH', label: 'Starts With' },
  { value: 'ENDSWITH', label: 'Ends With' },
  { value: 'LIKE', label: 'Like' },
  { value: 'NOT LIKE', label: 'Not Like' },
  { value: 'ISEMPTY', label: 'Is Empty' },
  { value: 'ISNOTEMPTY', label: 'Is Not Empty' },
  { value: 'IN', label: 'In' },
  { value: 'NOT IN', label: 'Not In' },
  { value: 'ANYTHING', label: 'Anything' },
  { value: 'BETWEEN', label: 'Between' },
  { value: 'SAMEAS', label: 'Is Same' },
  { value: 'NSAMEAS', label: 'Is Different' },
  { value: 'ON', label: 'On' },
  { value: 'ONToday', label: 'On Today' },
  { value: 'NOTONToday', label: 'Not On Today' },
  { value: 'DATEPART', label: 'Date Part' },
  { value: 'RELATIVEGE', label: 'Relative (on or after)' },
  { value: 'RELATIVELE', label: 'Relative (on or before)' },
  { value: 'RELATIVEGT', label: 'Relative (after)' },
  { value: 'RELATIVELT', label: 'Relative (before)' },
  { value: 'RELATIVEEE', label: 'Relative (on)' },
  { value: 'MORETHAN', label: 'Is More than' },
  { value: 'LESSTHAN', label: 'Is Less than' },
  { value: 'GT_FIELD', label: 'Greater than field' },
  { value: 'LT_FIELD', label: 'Less than field' },
  { value: 'GT_OR_EQUALS_FIELD', label: 'Greater than or is field' },
  { value: 'LT_OR_EQUALS_FIELD', label: 'Less than or is field' },
];
export const FILTER_VALUES: any = {
  active: [
    { label: 'True', value: 'true' },
    { label: 'False', value: 'false' },
  ],
  grafanaTimestamps: [
    { label: 'Grafana Start Time', value: '$__timeFrom()' },
    { label: 'Grafana End Time', value: '$__timeTo()' },
    { label: 'Grafana Time Range', value: '$__timeFilter()' },
    { label: 'Today', value: 'Today@javascript:gs.beginningOfToday()@javascript:gs.endOfToday()' },
    { label: 'Yesterday', value: 'Yesterday@javascript:gs.beginningOfYesterday()@javascript:gs.endOfYesterday()' },
    { label: 'Tomorrow', value: 'Tomorrow@javascript:gs.beginningOfTomorrow()@javascript:gs.endOfTomorrow()' },
    { label: 'This week', value: 'This week@javascript:gs.beginningOfThisWeek()@javascript:gs.endOfThisWeek()' },
    { label: 'Last week', value: 'Last week@javascript:gs.beginningOfLastWeek()@javascript:gs.endOfLastWeek()' },
    { label: 'Next week', value: 'Next week@javascript:gs.beginningOfNextWeek()@javascript:gs.endOfNextWeek()' },
    { label: 'This month', value: 'This month@javascript:gs.beginningOfThisMonth()@javascript:gs.endOfThisMonth()' },
    { label: 'Last month', value: 'Last month@javascript:gs.beginningOfLastMonth()@javascript:gs.endOfLastMonth()' },
    { label: 'Next month', value: 'Next month@javascript:gs.beginningOfNextMonth()@javascript:gs.endOfNextMonth()' },
    { label: 'Last 3 months', value: 'Last 3 months@javascript:gs.beginningOfLast3Months()@javascript:gs.endOfLast3Months()' },
    { label: 'Last 6 months', value: 'Last 6 months@javascript:gs.beginningOfLast6Months()@javascript:gs.endOfLast6Months()' },
    { label: 'Last 9 months', value: 'Last 9 months@javascript:gs.beginningOfLast9Months()@javascript:gs.endOfLast9Months()' },
    { label: 'Last 12 months', value: 'Last 12 months@javascript:gs.beginningOfLast12Months()@javascript:gs.endOfLast12Months()' },
    { label: 'This quarter', value: 'This quarter@javascript:gs.beginningOfThisQuarter()@javascript:gs.endOfThisQuarter()' },
    { label: 'Last quarter', value: 'Last quarter@javascript:gs.beginningOfLastQuarter()@javascript:gs.endOfLastQuarter()' },
    { label: 'Last 2 quarters', value: 'Last 2 quarters@javascript:gs.beginningOfLast2Quarters()@javascript:gs.endOfLast2Quarters()' },
    { label: 'Next quarter', value: 'Next quarter@javascript:gs.beginningOfNextQuarter()@javascript:gs.endOfNextQuarter()' },
    { label: 'Next 2 quarters', value: 'Next 2 quarters@javascript:gs.beginningOfNext2Quarters()@javascript:gs.endOfNext2Quarters()' },
    { label: 'This year', value: 'This year@javascript:gs.beginningOfThisYear()@javascript:gs.endOfThisYear()' },
    { label: 'Last year', value: 'Last year@javascript:gs.beginningOfLastYear()@javascript:gs.endOfLastYear()' },
    { label: 'Next year', value: 'Next year@javascript:gs.beginningOfNextYear()@javascript:gs.endOfNextYear()' },
    { label: 'Last 2 years', value: 'Last 2 years@javascript:gs.beginningOfLast2Years()@javascript:gs.endOfLast2Years()' },
    { label: 'Last 7 days', value: 'Last 7 days@javascript:gs.beginningOfLast7Days()@javascript:gs.endOfLast7Days()' },
    { label: 'Last 30 days', value: 'Last 30 days@javascript:gs.beginningOfLast30Days()@javascript:gs.endOfLast30Days()' },
    { label: 'Last 60 days', value: 'Last 60 days@javascript:gs.beginningOfLast60Days()@javascript:gs.endOfLast60Days()' },
    { label: 'Last 90 days', value: 'Last 90 days@javascript:gs.beginningOfLast90Days()@javascript:gs.endOfLast90Days()' },
    { label: 'Last 120 days', value: 'Last 120 days@javascript:gs.beginningOfLast120Days()@javascript:gs.endOfLast120Days()' },
    { label: 'Current hour', value: 'Current hour@javascript:gs.beginningOfCurrentHour()@javascript:gs.endOfCurrentHour()' },
    { label: 'Last hour', value: 'Last hour@javascript:gs.beginningOfLastHour()@javascript:gs.endOfLastHour()' },
    { label: 'Last 2 hours', value: 'Last 2 hours@javascript:gs.beginningOfLast2Hours()@javascript:gs.endOfLast2Hours()' },
    { label: 'Current minute', value: 'Current minute@javascript:gs.beginningOfCurrentMinute()@javascript:gs.endOfCurrentMinute()' },
    { label: 'Last minute', value: 'Last minute@javascript:gs.beginningOfLastMinute()@javascript:gs.endOfLastMinute()' },
    { label: 'Last 15 minutes', value: 'Last 15 minutes@javascript:gs.beginningOfLast15Minutes()@javascript:gs.endOfLast15Minutes()' },
    { label: 'Last 30 minutes', value: 'Last 30 minutes@javascript:gs.beginningOfLast30Minutes()@javascript:gs.endOfLast30Minutes()' },
    { label: 'Last 45 minutes', value: 'Last 45 minutes@javascript:gs.beginningOfLast45Minutes()@javascript:gs.endOfLast45Minutes()' },
    { label: 'One year ago', value: 'One year ago@javascript:gs.beginningOfOneYearAgo()@javascript:gs.endOfOneYearAgo()' },
  ],
};
